cloud: {{ env["ANYSCALE_CLOUD_ID"] }}
region: us-west-2

# 1 g4dn.4xlarge node --> 16 CPUs, 1 GPU
head_node_type:
  name: head_node_type
  instance_type: g4dn.4xlarge

max_workers: 0

aws:
  TagSpecifications:
    - ResourceType: "instance"
      Tags:
        - Key: ttl-hours
          Value: '24'