loud: {{ env["ANYSCALE_CLOUD_ID"] }}
region: us-west1

# 1 n1-standard-16-nvidia-tesla-t4-1 node --> 16 CPUs, 1 GPU
head_node_type:
  name: head_node_type
  instance_type: n1-standard-16-nvidia-tesla-t4-1

max_workers: 0
