cloud_id: {{ env["ANYSCALE_CLOUD_ID"] }}
region: us-west-2

# 1 m5.2xlarge node --> 8 CPUs
head_node_type:
  name: head_node_type
  instance_type: m5.2xlarge

max_workers: 0

aws:
  TagSpecifications:
    - ResourceType: "instance"
      Tags:
        - Key: ttl-hours
          Value: '24'