cloud: anyscale_v2_default_cloud
max_workers: 0
allowed_azs:
- us-west-2a
head_node_type:
  name: head_node_type
  instance_type: m5.2xlarge
worker_node_types:
- name: cpu_worker
  instance_type: m5.2xlarge
  min_workers: 3
  max_workers: 3
