cloud: anyscale_gce_cloud
allowed_azs:
- us-west1-a
head_node_type:
  name: head_node_type
  instance_type: n2-standard-8
worker_node_types:
- name: cpu_worker
  instance_type: n2-standard-8
  min_workers: 3
  max_workers: 3
